Atmosphere/atmosphere

modules/cpr/src/main/java/org/atmosphere/websocket/WebSocket.java
@jfarcand
here is the PR for the above issue.
regards, aki
=> #1846 atmosphere's WebSocket not using the right Response?

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java, modules/cpr/src/main/java/org/atmosphere/util/IOUtils.java
Binary message gets truncated 3 characters / 6 bytes.
=> #1873 Fix binary message

modules/cpr/src/main/java/org/atmosphere/cpr/ApplicationConfig.java, modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereConfig.java
If the init parameter does not exists in servlet configuration, also check the servlet context for it.
=> getInitParameter also from ServletContext

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereSession.java
Hello,
the AtmosphereSession is now extensible. Could this also land in 2.2.x / 2.3.x?
=> made AtmosphereSession members protected so that the class is extensible

modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcaster.java
- endBroadcast was not correctly removing cached entries in some cases.
- small code clean up
=> - cleaned up / fixed cache handling in DefaultBroadcaster

modules/cpr/src/main/java/org/atmosphere/cpr/AsynchronousProcessor.java, modules/cpr/src/test/java/org/atmosphere/cpr/AtmosphereInterceptorTest.java
Fix for https://github.com/Atmosphere/atmosphere/issues/2073
=> AtmosphereInterceptor.postInspect() is not called in case of a handler thrown exception

modules/cpr/src/main/java/org/atmosphere/config/managed/Invoker.java, modules/cpr/src/main/java/org/atmosphere/container/EmbeddedWebSocketHandler.java, modules/cpr/src/main/java/org/atmosphere/container/JSR356Endpoint.java, modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java, modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereRequestImpl.java, modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereResourceImpl.java, modules/cpr/src/main/java/org/atmosphere/cpr/DefaultAnnotationProcessor.java, modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcaster.java, modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcasterFactory.java, modules/cpr/src/main/java/org/atmosphere/interceptor/AtmosphereResourceStateRecovery.java, modules/cpr/src/main/java/org/atmosphere/websocket/DefaultWebSocketProcessor.java, modules/cpr/src/main/java/org/atmosphere/websocket/WebSocket.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1155 - “Collection.isEmpty() should be used to test for emptiness”. You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1155
Please let me know if you have any questions.
Ahmed
=> Code quality fix - Collection.isEmpty() should be used to test for emptiness

modules/cpr/src/main/java/org/atmosphere/cpr/SessionSupport.java
See:  https://github.com/Atmosphere/atmosphere/issues/2137
=> See: https://github.com/Atmosphere/atmosphere/issues/2137

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java
This allows for redeploy to properly work.
=> Fix exception preventing proper shutdown of Atmosphere.

modules/cpr/src/main/java/org/atmosphere/cache/AbstractBroadcasterCache.java, modules/cpr/src/main/java/org/atmosphere/cache/CacheMessage.java, modules/cpr/src/main/java/org/atmosphere/cache/SessionBroadcasterCache.java, modules/cpr/src/main/java/org/atmosphere/cache/UUIDBroadcasterCache.java, modules/cpr/src/main/java/org/atmosphere/interceptor/HeartbeatInterceptor.java, modules/cpr/src/test/java/org/atmosphere/cpr/BroadcasterCacheTest.java, modules/cpr/src/test/java/org/atmosphere/cpr/DefaultBroadcasterTest.java
Fixing 
ISSUE #2144 - corrected info logger message
ISSUE #2199 - invoking broadcaster listener upon daemon messages deletion by adding broadcaster id to CacheMessage.
=> ISSUE #2144 and ISSUE #2199

modules/cpr/src/main/java/org/atmosphere/interceptor/JavaScriptProtocol.java
Send the protocolMessage when there is no delay.
=> Fix for issue #2224

modules/cpr/src/main/java/org/atmosphere/handler/ReflectorServletProcessor.java
Keep the order of filters by adding them to a List instead of a Set.
=> Fix issue #2227

modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcaster.java, modules/cpr/src/main/java/org/atmosphere/interceptor/IdleResourceInterceptor.java, modules/cpr/src/test/java/org/atmosphere/cpr/BroadcasterTest.java
Changed IdleResourceInterceptor logger from ERROR to WARN
Fixing broadcaster memory leak issue
=> ISSUE #2214 and ISSUE #2186

modules/runtime/pom.xml
Adding only the needed JavaEE specs as a dependency.
=> depend only on needed JavaEE specs

modules/runtime/pom.xml
Servlet dependency should be provided
=> Define servlet dependency as provided

modules/cpr/src/main/java/org/atmosphere/container/AbstractJetty9AsyncSupportWithWebSocket.java, modules/cpr/src/main/java/org/atmosphere/container/Jetty93AsyncSupportWithWebSocket.java, modules/cpr/src/main/java/org/atmosphere/cpr/DefaultAsyncSupportResolver.java, pom.xml
Supports later versions of Jetty 9.3 and 9.4
=> Added Jetty93AsyncSupportWithWebSocket

modules/cpr/src/main/java/org/atmosphere/container/JSR356Endpoint.java
Details: https://github.com/Atmosphere/atmosphere/pull/2240
=> Reduced WebSocket onError log message to debug.

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereRequestImpl.java
Fixed a ConcurrentModificationException caused by more threads that access to the methods removeAttribute and getAttributeNames
=> Fixed a ConcurrentModificationException

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java
Add Content-Type with charset to first response (#2312 )
=> Add Content-Type to first response (#2312 )

modules/runtime/src/main/java/org/atmosphere/interceptor/HeartbeatInterceptor.java, modules/runtime/src/main/java/org/atmosphere/util/IOUtils.java
=> HeartbeatInterceptor should respect content of the GET method

modules/cpr/pom.xml, modules/native/pom.xml
=> Define requirements and capabilities for using ServiceLoader to load Injectables in OSGI environment

modules/runtime/src/main/java/org/atmosphere/runtime/AtmosphereResourceImpl.java
=> Fix the integer overflow in AtmosphereResource#suspend

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java, modules/cpr/src/test/java/org/atmosphere/cpr/AtmosphereFrameworkTest.java
=> lookupDefaultBroadcasterType interprets AUTODETECT_BROADCASTER properly

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereRequestImpl.java
=> Fix NPE on getCookies method

modules/cpr/src/main/java/org/atmosphere/cpr/ContainerInitializer.java
Fix https://github.com/Atmosphere/atmosphere/issues/2367
=> Fix #2367 WebSocket protocol not supported on Payara 5

modules/cpr/src/main/java/org/atmosphere/container/JSR356Endpoint.java, modules/cpr/src/main/java/org/atmosphere/util/ReaderInputStream.java, modules/cpr/src/main/java/org/atmosphere/util/uri/UriComponent.java, modules/cpr/src/main/java/org/atmosphere/websocket/DefaultWebSocketProcessor.java, modules/cpr/src/main/java/org/atmosphere/websocket/WebSocket.java
Fix for https://github.com/Atmosphere/atmosphere/issues/2385.
=> fix ByteBuffer and CharBuffer incompatibilities across JDKs

modules/cpr/src/main/java/org/atmosphere/websocket/WebSocket.java
There was this issue https://github.com/Atmosphere/atmosphere/issues/2032 but no PR was submitted. Nettosphere PR is https://github.com/Atmosphere/nettosphere/pull/148.
=> Allow WebSocket to close with code and reason

modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcasterFactory.java
#2390 in DefaultBroadcaster.lookup() the synchronized(c) block should be avoided
#2389 in DefaultBroadcaster.lookup() the call to store.getId() is made twice but once should be enough
=> #2390 in DefaultBroadcaster.lookup() the synchronized(c) block should be avoided

modules/cpr/src/main/java/org/atmosphere/cpr/AsynchronousProcessor.java, modules/cpr/src/main/java/org/atmosphere/util/Utils.java
@jfarcand Here's the fix as we've discussed. I'm not happy about the check for 'in test'. The tests should be fixed instead.
Cheers!
=> Fixes #2143. Handle mismatch between Atmosphere and the server

modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcaster.java
Fix #2436, [#1822](https://github.com/Atmosphere/atmosphere/issues/1822)
=> Fix push message are not processed randomly

pom.xml
See reported issue: https://github.com/Atmosphere/atmosphere/issues/2439
=> Added <doclint>none

modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcaster.java
... in DefaultBroadcaster.java
=> Fix a bad comparison between a String and a Class object

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java
updated misleading documentation
=> Fix for Atmosphere/atmosphere#2514
