Atmosphere/atmosphere

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java

Moved some code to populate excludedInterceptors from configureAtmosphereInterceptor(ServletConfig sc) to doInitParams(ServletConfig sc, boolean reconfigure). This way, excludedInterceptors is populated early enough and AnnotationUtil can pick it up.

#1857 populate excludedInterceptors in doInitParams

---

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereResponse.java

Modified AtmosphereResponse to separate header lines with "\r\n" according to RFC-2616

Generate standard HTTP header

---

modules/cpr/src/main/java/org/atmosphere/interceptor/AtmosphereResourceStateRecovery.java

* Iterate all the tracker IDs, filter, and then add any filtered
messages to the same cached message list to process.
Inside the loop over the broadcaster IDs, the cachedMessages keeps getting re-assigned to the results of filtering the messages for that specific broadcaster ID.
It seems to me the real intent is the following:
* Iterate broadcaster IDs.
* For a given ID, lookup cached messages.
* Filter those cached messages.
* If any message are left after filtering, add to our aggregate list.
* Return the aggregate list of all filtered messages to the calling code.
This fix seems to restore that logic.
Any chance we can get this merged into the 2.2.x branch as well for a release any time soon? This state recovery being broken is a blocker for our project.
Thanks again.

Fix some merge issues w/ state recovery interceptor.

---

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereSession.java

Hello,
this change will treat long-polling resources as single-use which means that subsequent calls to tryAcquire(t) will have to wait until the client reconnects. This should avoid the problem where the same resource is used by e.g. two threads at the same time, to write something to one client.
It shouldn't break the functionality for others who use Comet / SSE / WebSockets but if need be, I could create a new method with this behavior to keep backwards-compatibility.
Could this get merged into 2.2.x / 2.3.x?

AtmosphereSession: treat long-polling resources as single-use

---

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java

When set:
```java atmosphereServlet.setInitParameter(ApplicationConfig.BROADCASTER_FACTORY, RedisBroadcasterFactory.class.getName());```
Create new instances of Factory.

Create new instances when broadcaster is defined on config

---

modules/cpr/src/main/java/org/atmosphere/cpr/DefaultAsyncSupportResolver.java
modules/cpr/src/test/java/org/atmosphere/cpr/DefaultAsyncSupportResolverTest.java

Do not return BlockingIOCometSupport in case the WebSocket class cannot be found. Callers of newCometSupport all handle null values and apply a default for AsyncSupport.
This fixes an issue on WebLogic 12.1.3 when the JSR356AsyncSupport fails. The fix will result in Servlet30CometSupport since servlet 3.0 async is available.
The fix has been tested on WebLogic 12.1.3 (now fallbacks to Servlet30). Also verified no regression for Jetty 9.3 with WebSocket (correctly resolves the WebSocket class).
Note#1: I've added a FIXME regarding AsyncSupportResolver.resolve since the parameters in the interface is named differently from the method in the implementing class DefaultAsyncSupportResolver. This should be looked at.
Note#2: I've also observed that DefaultAsyncSupportResolver.resolve(boolean, …

#2018: [WebLogic] 12.1.3 BlockingIOCometSupport selected

---

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereResourceImpl.java
modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcaster.java
modules/cpr/src/main/java/org/atmosphere/websocket/DefaultWebSocketProcessor.java

Fix for atmosphere#2052
Although I'm not exactly sure whether the call to dirtyClose needs to be there in the delayed close case, but I don't think it hurts.

Prevent duplicate resource warning for delayed close websocket connections

---

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java

If not removed the shutdown handlers leaks the thread which holds on to the AtmosphereFramework.

Prevent shutdown handler from leaking on orderly shutdown.

---

modules/cpr/src/main/java/org/atmosphere/container/Jetty9AsyncSupportWithWebSocket.java

This change is to support websocket extensions (for example, compression) in Jetty 9.3.x servers

Add support for websocket extensions in Jetty 9.3.x

---

modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedAtmosphereHandler.java
modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java
modules/cpr/src/main/java/org/atmosphere/util/AtmosphereConfigReader.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1132 - “Strings literals should be placed on the left side when checking for equality”. You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1132
Please let me know if you have any questions.
Ahmed

Code quality fix - Strings literals should be placed on the left side when checking for equality

---

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereServlet.java
modules/cpr/src/main/java/org/atmosphere/cpr/MeteorServlet.java
modules/cpr/src/main/java/org/atmosphere/handler/ReflectorServletProcessor.java
modules/cpr/src/main/java/org/atmosphere/websocket/DefaultWebSocketProcessor.java
modules/cpr/src/main/java/org/atmosphere/websocket/protocol/SimpleHttpProtocol.java
modules/native/src/main/java/org/atmosphere/cpr/AtmosphereServlet.java

This pull request is focused on resolving occurrences of Sonar rule squid:S2057 - “Serializable classes should have a version id”. You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2057
Please let me know if you have any questions.
Ahmed

Code quality fix - Serializable classes should have a version id

---

modules/cpr/src/main/java/org/atmosphere/websocket/WebSocket.java
modules/cpr/src/main/java/org/atmosphere/websocket/protocol/ProtocolUtil.java

This fixes a ConcurrentModificationException when a request websocket frame comes in and a websocket response is in process at the same time. I have created a test in the Nettosphere project that replicates the issue. It shows thats Atmosphere fails before this PR, and it is successful with this PR.

Fix ConcurrentModificationException.

---

modules/cpr/src/main/java/org/atmosphere/cache/UUIDBroadcasterCache.java
modules/cpr/src/test/java/org/atmosphere/cpr/UUIDBroadcasterCacheTest.java

Using concurrentLinkedQueue rather than ClientQueue to fix long-polling missing messages

Issue #2063: duplicate messages will be overriden with the help of

---

modules/cpr/src/main/java/org/atmosphere/interceptor/JSONPAtmosphereInterceptor.java

Can't see why this wouldn't be safe to optimize :)

More compact JSON data for JSONP transport, save 2 bytes for every response

---

modules/cpr/src/main/java/org/atmosphere/util/CookieUtil.java

CookieUtil memory leak on tomcat 8.0.28 shutdown
Avoid creation of threadLocal for caching simpleDateFormat object -  instead  creating new one every time for the construction of response headers.
https://github.com/Atmosphere/atmosphere/issues/2221

ISSUE #2221 : Memory leak fix for SimpleDateFormat

---

modules/cpr/src/main/java/org/atmosphere/container/JSR356Endpoint.java

Hey guys!
While working on `Apache CXF` and `Websockets` integration (using awesome `Atmosphere`, surely), we have noticed very weird behavior related to `JSR-356` Websockets bridge (`JSR256Endpoint`). `Atmosphere` tries hard to workaround the inconsistencies regarding request URL/URI and also consults the 'Origin' header. For some reason, the the 'Origin' header may contain a `null` as string value (not a Java `null`) and it leads to cumbersome request URLs like 'null/demo/ws'. This small PR tries to address that in adhoc fashion.
Thank you.
Best Regards,
Andriy Redko

Fixed the weird case when 'Origin' header contains 'null' string

---

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereResponseImpl.java

Fixes problem described here: https://github.com/Atmosphere/atmosphere/issues/1783#issuecomment-339526412 
As you can see in Jetty sources (https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/ServletUpgradeResponse.java#L74), it uses `setHeader` with `null` value to remove header. JavaDoc doesn't mention `null` values, but I don't think that it's a good idea to replace `null` with empty string.

Headers handling should not replace null with empty string

---

modules/runtime/src/main/java/org/atmosphere/websocket/DefaultWebSocketProcessor.java

If you click on a download link in Firefox, then the websocket is disconnected briefly until Firefox realizes it is a download request. The reconnect then happens in less than 1 second so the new connection will be closed on the server after the timeout of 1s has elapsed (when the code tries to close an old connection). After this the websocket connection will not work.

Do not close a reconnected websocket

---

modules/runtime/src/main/java/org/atmosphere/container/JSR356AsyncSupport.java

Previously for a servlet mapped using /mapping/*, there were mappings done for:
* /mapping
* /mapping/{path1}
* /mapping/{path1}/{path2}
etc
which do not match /mapping/

Register websocket endpoints for /mapping/ for /mapping/* servlets

---

modules/runtime/src/main/java/org/atmosphere/runtime/Universe.java

The previous version causes a lot of logging about Universe not being reliable
even though you never use Universe. This changes the behavior so that you will
instead get an exception only when actually using the methods, when they will not
work properly.

Throw exception if Universe methods are used when they are not reliable

---

modules/runtime/src/main/java/org/atmosphere/container/JSR356AsyncSupport.java
modules/runtime/src/main/java/org/atmosphere/util/IOUtils.java
modules/runtime/src/test/java/org/atmosphere/util/IOUtilsTest.java

After some digging about #2316 (and #2326) I came to a conclusion that servlet mapping with trailing slash is incorrect in `JSR 356` [1]. The mapping value must have a leading '/' and should not contain empty parts:
> The value attribute must be a Java string that is a partial URI or URI-template (level-1), with a leading
‘/’. For a definition of URI-templates, see [6]. The implementation uses the value attribute to deploy the
endpoint to the URI space of the websocket implementation. The implementation must treat the value as relative to the root URI of the websocket implementation in determining a match against the request URI of an incoming opening handshake request. [WSC-4.1.1-2] The semantics of matching for annotated endpoints is the same as was defined in the previous chapter. The …

Resolve an issue with the servlet mapping for JSR 356

---

modules/runtime/src/main/java/org/atmosphere/runtime/AtmosphereResourceImpl.java

It helps to create custom AtmosphereResource with its own "uuid" by overriding AtmosphereResourceImpl.

AtmosphereResourceImpl is modified to use only the "uuid()" method to refer uuid

---

modules/cpr/src/main/java/org/atmosphere/container/TomcatWebSocketUtil.java
pom.xml

According to https://tomcat.apache.org/tomcat-7.0-doc/changelog.html#Tomcat%207.0.93%20(violetagg)/Other, Tomcat 7.0.93 is capable to compile and execute on Java 11.
This PR updates the Tomcat 7 dependency to Tomcat 7.0.93 and replaces the deprecated org.apache.catalina.util.Base64 with org.apache.tomcat.util.codec.binary.Base64, thus enabling Atmosphere 2.5.x to run on Java 11.

Update Tomcat 7 version to 7.0.93 (runnable on Java 11)

---

modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcaster.java

DefaultBroadcaster#deliverPush() caches the message, sends the push, and then restores the message to the Deliver object, since it may mutate the message inside the object. This changes the logic to cache the raw message, rather than message.toString().

Fixes #2383

---

modules/cpr/src/main/java/org/atmosphere/container/JSR356Endpoint.java

When WebSocket connection is established to Spring Boot 2 application, org.atmosphere.container.JSR356Endpoint does NOT properly handle request cookies.
As a result AtmosphereRequest does not contain cookies at all although cookies are available in the request header...
Wrong header name was used "Cookie" instead of  "cookie"

Handling cookies problem in Tomcat 9.0.27

---

modules/cpr/src/main/java/org/atmosphere/cpr/ApplicationConfig.java
modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java

Content-type header are missing to first response. we use atmosphere-projet 2.2.13 
[ from Atmosphere 2312](https://github.com/Atmosphere/atmosphere/issues/2312)
It is possible to release a new version and push it to Maven Central ?
thank's

add content type to first response

---

modules/cpr/src/main/java/org/atmosphere/util/Utils.java

When invoke on an Atmosphere managed bean fails, it should definitely show up as ERROR, not as DEBUG within the logging.

error log such important exception

---

modules/cpr/src/main/java/org/atmosphere/container/JSR356AsyncSupport.java

Some API like Wildfly undertow does not enable this extension in manually created Endpoints.
Fix bug #2039

Support for per-message deflate Websocket extension

---

modules/cpr/pom.xml

[#2415 ](https://github.com/Atmosphere/atmosphere/issues/2415) dependency conflict issue for org.eclipse.jetty:jetty-http:jar

fix dependency conflict issue

---

modules/cpr/pom.xml

Quarkus is defined as optional in JSR356AsyncSupport hence the OSGI
metadata should reflect that.
Fixes #2453

Marking quarkus as optional in the OSGI MANIFEST

---

modules/cpr/pom.xml

org.atmosphere.jersey.util is not a mandatory requirement for the
runtime module. This change updates the generated OSGi manifest to
reflect that.
Fixes #2461

org.atmosphere.jersey.util should be optional in the OSGi manifest

---

modules/cpr/pom.xml

atmosphere-runtime requires testng lib even if not used in runtime

Set testng library with resolution optional

---

modules/cpr/src/main/java/org/atmosphere/cpr/BroadcasterLifeCyclePolicy.java
modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcasterFactory.java
modules/cpr/src/main/java/org/atmosphere/lifecycle/LifecycleHandler.java
modules/cpr/src/test/java/org/atmosphere/cpr/BroadcasterLifecyclePolicyTest.java

This commit adds a new lifecycle policy where a broadcaster is destroyed iff the idle time has expired + there are no resources (aka it's empty).

#2468: added IDLE_EMPTY_DESTROY broadcaster lifecycle policy

---

modules/cpr/pom.xml
modules/cpr/src/main/java/org/atmosphere/container/JSR356AsyncSupport.java

PR for Issue 2473
- adds MANIFEST entry 'Eclipse-BuddyPolicy: registered' to allow loading of the custom AtmosphereHandler class from inside the atmosphere-runtime inside the equinox OSGi environment
- overwrites 3 methods in JSR356AsyncSupport.AtmosphereConfigurator to avoid RuntimeExceptions in equinox OSGi environment during initialization of javax.websocket implementation

Issue2473 websocket handshake fails jetty10

---

modules/cpr/src/main/java/org/atmosphere/container/Jetty9WebSocketHandler.java

Client errors like timeouts and EOFs are currently logged as errors. While this is probably useful in development, on instances with many connected clients it will likely just be noise.
At the moment, log rows like these are quite common:
```
2022-11-14 08:11:32 ERROR [o.a.c.Jetty9WebSocketHandler] ::
org.eclipse.jetty.io.EofException: null
at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:279)
at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381)
at org.eclipse.jetty.websocket.common.io.FrameFlusher.flush(FrameFlusher.java:264)
at org.eclipse.jetty.websocket.common.io.FrameFlusher.process(FrameFlusher.java:193)
at …
```

Reduce log level for client errors in Jetty 9 WebSocket handler

---

modules/cpr/src/main/java/org/atmosphere/util/annotation/InputStreamIterator.java

This broke in 412463d0ced979d9219cf6409d674b6ce79f09a1 when the field initialization was moved from the field declaration to the constructor.

Fix NPE in InputStreamIterator

---

modules/cpr/src/main/java/org/atmosphere/container/JSR356Endpoint.java

Fixes https://github.com/Atmosphere/atmosphere/issues/2502
Behavior when using Jetty 9 was that attributes added by filters were copied from the HTTPRequest to the AtmosphereRequest. In Jetty 10, we are using JSR356Endpoint which does not copy the attributes. I couldn't figure out how to get the request attributes but instead will settle for using the attributes on the handshakeSession.

JSR356Endpoint to read attributes from the handshake session

---

README.md

The initial recommendation to use ChatGPT for assistance may lead to potentially unreliable sources of info.
While LLMs have made significant strides in assisting with coding and technical documentation, they're nothing more than glorified autocorrect engines on steroids, and as such are known to occasionally produce hallucinations that seem plausible but are factually incorrect or misleading.
This is a problem in technical settings where precision is key.

Add a Proper Getting Started Section

---

modules/cpr/src/main/java/org/atmosphere/container/JSR356Endpoint.java
modules/cpr/src/test/java/org/atmosphere/container/version/JSR356WebSocketTest.java

Without this, it's impossible to know if a connection is done using SSL or not.

Copy `isSecure()` property from JSR356 `Session`

---

pom.xml

Make the Import-Package version range for jakarta.servlet valid by OSGI standards. Discussion in #2511.

Fix servlet import-package version (#2511)

---

modules/cpr/src/main/java/org/atmosphere/util/AtmosphereConfigReader.java

The **AtmosphereConfigReader** that is used to read Atmosphere configuration when initializing AtmosphereServlets parses XML files without security settings on or external entities disabled, which could lead to SSRF, information leaks, etc. 
Though so far it does not look like a critical one because malicious users has to get access to the application to inject XML files

Set FEATURE_SECURE_PROCESSING for DocumentBuilderFactory to remediate XXE (XML External Entity Injection) vulnerabilities

---

modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java

`null` check after `String.trim()` doesn't make sense. It leads to NPE

Avoid NullPointerException if inputLine is 'null'
